#!/bin/sh

# print config if requested
case $1 in
   config)
        cat << 'EOM'
graph_title Temperature / Humidity
graph_vlabel temp[‹C] / humid[%]
graph_info Temperature and humidity measured with Aosong's DHT12 sensor.
temperature.label temperature
temperature.info Temperature measured with DHT12.
humidity.label humidity
humidity.info Humidity measured with DHT12.
EOM

        exit 0;;
esac

# measure temperature and humidity with dht12
temp_humid=`/usr/local/bin/dht12` || exit 1

# print the result in Munin plugin format
printf "temperature.value "; echo $temp_humid | cut -d ' ' -f1
printf "humidity.value "; echo $temp_humid | cut -d ' ' -f2
