#!/bin/sh

# print config if requested
case $1 in
   config)
        cat << 'EOM'
graph_title Temperature
graph_vlabel temperature[C]
graph_category dht12
graph_info Temperature measured with Aosong's DHT12 sensor.
temperature.label temperature
temperature.info Temperature measured with DHT12.
EOM

        exit 0;;
esac

# measure temperature and humidity with dht12
temp_humid=`sleep 1; /usr/local/bin/dht12` || exit 1

# print temperature in Munin plugin format
printf "temperature.value "; echo $temp_humid | cut -d ' ' -f1
